export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};
import Sidebar from "@/components/Sidebar/Sidebar";
import ".././styles/globals.css";

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ja">
            <head>
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Russo+One&amp;display=swap"
                    rel="stylesheet"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap"
                    rel="stylesheet"
                ></link>
            </head>
            <body>
                <div className="flex justify-between">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
}
