export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};
import Sidebar from "@/components/Sidebar/Sidebar";
import "../../../styles/globals.css";

export default function Layout({ children }: { children: React.ReactNode }) {
    VANTA.CLOUDS({
        el: "#sky",
        mouseControls: true,
        touchControls: true,
        gyroControls: false,
        minHeight: 200.0,
        minWidth: 200.0,
        backgroundColor: 0xc7d7eb,
        skyColor: 0x8bc2e1,
        cloudColor: 0xbbcced,
        sunColor: 0xff8418,
        sunlightColor: 0xff7f00,
    });
    return (
        <html lang="ja">
            <head>
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Russo+One&amp;display=swap"
                    rel="stylesheet"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap"
                    rel="stylesheet"
                ></link>
                <script src="three.r134.min.js"></script>
                <script src="vanta.clouds.min.js"></script>
            </head>
            <body>
                <div className="flex justify-between overflow-hidden">
                    <Sidebar />
                    <div id="sky"></div>
                    {children}
                </div>
            </body>
        </html>
    );
}
