export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};
import MainHeader from "@/components/MainHeader/MainHeader";
import "../../styles/globals.css";

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="w-full">
            <MainHeader />
            {children}
        </div>
    );
}
