export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};
import "../../styles/globals.css";
import Header from "@/components/Header/Header";

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="w-full">
            <Header />
            {children}
        </div>
    );
}
